local_backend: true

backend:
  name: git-gateway
  branch: main

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/cms_media"

i18n:
  structure: multiple_folders
  locales: [en, gr]

collections:
  - name: "teamMembers"
    label: "Team Members / Προσωπικό"
    folder: "src/content_management_files/team_members"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Όνομα", name: "name", widget: "string", i18n: true}
      - {label: "Φωτογραφία προφίλ", name: "pfp", widget: "image", i18n: duplicate}
      - {label: "Ρόλος στο χημείο", name: "title", widget: "string", i18n: true}
      - {label: "Περιγραφή", name: "body", widget: "markdown", i18n: true}

  - name: "Offers"
    label: "Offers / Προσφορές"
    i18n:
      structure: single_file
      locales: [en, gr]
    files:
      - label: "Offers List / Λίστα Προσφορών"
        name: "Offers"
        file: "assets/js/offers2.json"
        i18n: true
        fields:
          - label: "Offers List"
            name: "offersList"
            widget: "list"
            i18n: true
            allow_add: true
            fields:
              - {label: "Description", name: "description", widget: "string", i18n: true}
              - {label: "Image", name: "image", widget: "image", i18n: duplicate}




  - name: "biomarkers"
    label: "Biomarkers / Βιοδεικτά Στοιχεία"
    folder: "src/content_management_files/biomarkers"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Όνομα Στοιχείου", name: "name", widget: "string", i18n: true}
      - {label: "Φωτογραφία Στοιχείου", name: "image", widget: "image", i18n: duplicate}
      - {label: "Μικρή περιγραφή στοιχείου", name: "shortDesc", widget: "string", i18n: true}
      - {label: "Περιγραφη", name: "body", widget: "markdown", i18n: true}


  - name: "services"
    label: "Services / Υπηρεσίες"
    folder: "src/content_management_files/services_provided"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Όνομα Υπηρεσίας", name: "name", widget: "string", i18n: true}
      - {label: "Φωτογραφία", name: "image", widget: "image", i18n: duplicate}
      - {label: "Περιγραφή", name: "body", widget: "markdown", i18n: true}


  - name: "about"
    label: "Πληροφορίες Βιοεξέλιξης"
    files:
      - label: "Πληροφορίες"
        name: "client"
        file: "src/data/client.json"
        fields:
          - {label: "E-mail", name: "email", widget: "string"}
          - {label: "domain", name: "domain", widget: "string", default: ["www.domain.com"]}
          - label: "Τηλέφωνα"
            name: "phoneForTel"
            widget: list
            allow_add: true
            label_singular: "νούμερο τηλεφώνου"
            summary: 'Τηλ.: {{fields.number}}'
            collapsed: true
            min: 1
            field: {label: "τηλεφωνο", name: "number", widget: "number"}


  - label: "Ερωτήσεις / Questions"
    name: "questions"
    folder: "src/content_management_files/frequently_asked_questions"
    create: true
    slug: "{{slug}}"
    i18n: true
    identifier_field: name
    fields:
      - {label: "Ερώτηση", name: "question", widget: "string", i18n: true}
      - {label: "Απάντηση", name: "body", widget: "markdown", i18n: true}